# v="department"
# print(v[3]+v[2]+v[3]+v[4]+v[5]+v[6]+v[7]+v[8]+v[9])

# print("python"[-1]) 
# print("python"[-2]) 
# print("python"[-3]) 
# print("python"[-4]) 
# print("python"[-5]) 
# print("python"[-6]) 
# print("python"[-7]) 

w="python"
# print(w[:]) 
# print(w[0:]) 
# print(w[0:6]) 
# print(w[0:0]) 
# print(w[0:1]) 
# print(w[0:2]) 
# print(w[0:3]) 
# print(w[0:4]) 
# print(w[0:5]) 
# print(w[0:6]) 
# print(w[0:7]) 
# print(w[0:99]) 
# print(w[0:0]) 
# print(w[3:2]) 
# print(w[5:3]) 
# print(w[0:-1]) 
# print(w[0:-2]) 
# print(w[0:-3]) 
# print(w[0:-4]) 
# print(w[0:-5]) 
# print(w[0:-6]) 
# print(w[0:-7]) 